mutation ($groupId: ID!){
  forkGroup(groupId: $groupId){
    groups{
      id
      name
      importance
      userId
      public
      ancestorGroups {
        id
        name
        userId
      }
    }
  }
}