query($id: ID!){
    user(id: $id)
    {
        groups{
            id
            name
            public
            tasks{
                id
                name
                importance
            }
        }
    }
}